version: 0.2
            
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - which jar
  build:
    commands:
      - jar -cvf poctomcat.war *
  post_build:
    commands:
      - echo "Building WAR file completed for tomcat"
artifacts:
  files:
    - poctomcat.war
    - buildspec.yml
    - appspec.yml
  name: poctomcat
  discard-paths: yes
